// vue/src/app/common/layouts/UnauthorizedLayout.vue
<template>
    <div
        class="flex items-center justify-center w-full min-h-screen relative overflow-hidden"
    >
        <div
            class="absolute bg-gradient-to-t from-primary to-transparent h-[550px] w-[550px] left-[-14rem] bottom-[-14rem] rounded-tl-[154px] rounded-tr-[123px] rounded-br-[234px] rounded-bl-[520px] rotate-[100deg] z-[-1] animate-spin-layout shadow-[0_0_45px_rgba(112,144,176,0.125)]"
        />
        <div
            class="absolute bg-gradient-to-t from-primary to-transparent h-[450px] w-[450px] right-[-14rem] top-[-14rem] rounded-tl-[54px] rounded-tr-[123px] rounded-br-[434px] rounded-bl-[20px] rotate-[108deg] z-[-1] animate-spin-layout shadow-[0_0_45px_rgba(112,144,176,0.125)]"
        />
        <Teleport to="body">
            <ToastList />
        </Teleport>

        <router-view v-slot="{ Component }">
            <transition name="unauth" mode="out-in">
                <component :is="Component" />
            </transition>
        </router-view>
    </div>
</template>

<script setup>
import ToastList from "../components/ToastList.vue";
</script>
<style>
.unauth-enter-active,
.unauth-leave-active {
    transition: 600ms ease all;
}

.unauth-enter-from,
.unauth-leave-to {
    opacity: 0;
}
</style>

// react/src/app/common/layouts/UnauthorizedLayout.jsx
import React from "react";
import { Outlet } from "react-router-dom";
import styled, { keyframes } from "styled-components";

export const UnauthorizedLayout = ({ children }) => {
    return (
        <Container>
            {children}
            <Outlet />
        </Container>
    );
};

export const animationBgElement = keyframes`
    from {
        transform: rotate(120deg);

    }

    to {

        transform: rotate(160deg);
    }
`;

export const Container = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    min-height: 100vh;
    position: relative;
    overflow: hidden;

    &:after {
        content: "";
        position: absolute;
        width: 550px;
        height: 550px;
        left: -14rem;
        bottom: -14rem;
        border-radius: 154px 123px 234px 520px;
        transform: rotate(100deg);
        background: linear-gradient(
            to top,
            ${({ theme }) => theme.colors.primary},
            transparent
        );
        z-index: -1;
        box-shadow: 0px 0px 45px ${({ theme }) => theme.colors.boxShadow};
        animation: ${animationBgElement} 8s ease infinite alternate;
    }

    &:before {
        content: "";
        position: absolute;
        width: 450px;
        height: 450px;
        right: -14rem;
        top: -14rem;
        border-radius: 54px 123px 434px 20px;
        transform: rotate(180deg);
        background: linear-gradient(
            to top,
            ${({ theme }) => theme.colors.primary},
            transparent
        );
        z-index: -1;
        box-shadow: 0px 0px 45px ${({ theme }) => theme.colors.boxShadow};
        animation: ${animationBgElement} 8s ease infinite alternate;
    }
`;
