// vue/src/app/Planner/components/Planner.vue
<template>
    <div class="wrapper">
        <div class="planner-container">
            <PlannerBlock
                v-for="item in days"
                v-model:recipes="recipes[item]"
                :date="item"
                :class="{
                    'planner-block--highlighted': item === getCurrentDay(),
                }"
                :loader="loader"
                ref="plannerBlocks"
            />
        </div>
    </div>
</template>
<script setup>
import PlannerBlock from "./PlannerBlock.vue";
import Recipe from "../models/Recipe.js";
import { onMounted, ref, computed, watch } from "vue";
import {
    getFirstDayOfWeek,
    getLastDayOfWeek,
    getCurrentDay,
    getDatesBetweenDays,
} from "../../common/utils/datesHelpers.js";

const props = defineProps({
    dateStart: {
        type: String,
        default: "",
    },
    dateEnd: {
        type: String,
        default: "",
    },
});

const dateStart = computed(() => props.dateStart || getFirstDayOfWeek());
const dateEnd = computed(() => props.dateEnd || getLastDayOfWeek());
const days = ref(getDatesBetweenDays(dateStart.value, dateEnd.value));
const loader = ref(true);
const recipes = ref({});
const plannerBlocks = ref([]);

onMounted(() => {
    const elementHighlighted = document.querySelector(
        ".planner-block--highlighted"
    );

    const elementPlannerContainer =
        document.querySelector(".planner-container");

    const { x: xCord } = elementHighlighted.getBoundingClientRect();

    elementPlannerContainer.scrollTo(xCord - 100, 0);
});

watch(
    [dateStart, dateEnd],
    () => {
        days.value = getDatesBetweenDays(dateStart.value, dateEnd.value);

        days.value.forEach((e) => {
            recipes.value[e] = [];
        });

        loader.value = true;
        Recipe.fetchUserRecipes({
            include: "image",
            dateStart: `${dateStart.value}`,
            dateEnd: `${dateEnd.value}`,
        })
            .then((res) => {
                res.forEach((e) => {
                    recipes.value[e.date].push(e);
                });
            })
            .finally(() => {
                loader.value = false;
            });
    },
    { immediate: true }
);
</script>
<style lang="scss" scoped>
.wrapper {
    grid-area: planner;
    background-color: $alpha;
    box-shadow: 0px 6px 24px $alpha-dark;
    border-radius: 16px;
    backdrop-filter: blur(25px);
    padding: 2rem;
    overflow: hidden;
}

.planner-container {
    height: 100%;
    width: 100%;
    display: flex;
    gap: 1rem;
    overflow-x: scroll;
    padding-left: 2rem;
    padding-bottom: 2rem;
}
</style>

// react/src/app/Dashboard/components/Planner.jsx
import React from "react";
import styled from "styled-components";
import { PlannerBlock } from "./PlannerBlock";

export const Planner = () => {
    return (
        <MainPlanner>
            <PlannerContainer>
                <PlannerBlock highlighted />
                <PlannerBlock />
                <PlannerBlock />
                <PlannerBlock />
                <PlannerBlock />
                <PlannerBlock />
                <PlannerBlock />
            </PlannerContainer>
        </MainPlanner>
    );
};

const MainPlanner = styled.div`
    grid-area: planner;
    background-color: rgba(255, 255, 255, 0.45);
    box-shadow: 0px 6px 24px rgba(0, 0, 0, 0.06);
    border-radius: 16px;
    backdrop-filter: blur(25px);
    padding: 2rem;
    overflow: hidden;
`;

const PlannerContainer = styled.div`
    height: 100%;
    width: 100%;
    display: flex;
    gap: 1rem;
    overflow-x: scroll;
    padding-left: 2rem;
    padding-bottom: 2rem;
`;
