// react/src/app/Dashboard/components/StatsPanel.jsx
import React from "react";
import styled from "styled-components";

export const StatsPanel = () => {
    return (
        <MainStats>
            <MainStatsHeader>
                <StatsHeaderTitle>
                    Statystyki (ilość kalorii dziennie)
                </StatsHeaderTitle>
                <StatsHeaderText>
                    Najbliższy plan tygodniowy (01.01.2020 - 07.01.2020)
                </StatsHeaderText>
            </MainStatsHeader>
            <MainStatsContainer>
                <StatsElement>
                    <StatsElementBar>
                        <StatsElementBarInner />
                    </StatsElementBar>
                    <StatsElementText>01/01</StatsElementText>
                </StatsElement>
                <StatsElement>
                    <StatsElementBar>
                        <StatsElementBarInner />
                    </StatsElementBar>
                    <StatsElementText>02/01</StatsElementText>
                </StatsElement>
                <StatsElement>
                    <StatsElementBar>
                        <StatsElementBarInner />
                    </StatsElementBar>
                    <StatsElementText>03/01</StatsElementText>
                </StatsElement>
                <StatsElement>
                    <StatsElementBar>
                        <StatsElementBarInner />
                    </StatsElementBar>
                    <StatsElementText>04/01</StatsElementText>
                </StatsElement>
                <StatsElement>
                    <StatsElementBar>
                        <StatsElementBarInner />
                    </StatsElementBar>
                    <StatsElementText>05/01</StatsElementText>
                </StatsElement>
                <StatsElement>
                    <StatsElementBar>
                        <StatsElementBarInner />
                    </StatsElementBar>
                    <StatsElementText>06/01</StatsElementText>
                </StatsElement>
                <StatsElement>
                    <StatsElementBar>
                        <StatsElementBarInner />
                    </StatsElementBar>
                    <StatsElementText>07/01</StatsElementText>
                </StatsElement>
            </MainStatsContainer>
        </MainStats>
    );
};

const MainStats = styled.div`
    grid-area: stats;
    background-color: rgba(255, 255, 255, 0.45);
    box-shadow: 0px 6px 24px rgba(0, 0, 0, 0.06);
    border-radius: 16px;
    backdrop-filter: blur(25px);
    padding: 2rem;
    display: flex;
    flex-direction: column;
`;

const MainStatsHeader = styled.div`
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    flex: 1;
`;

const StatsHeaderTitle = styled.div`
    font-size: 18px;
    font-weight: 800;
`;

const StatsHeaderText = styled.div`
    font-size: 12px;
    font-weight: 500;
    color: #aaa;
`;

const MainStatsContainer = styled.div`
    flex: 4;
    display: flex;
    justify-content: space-between;
    padding: 1rem 0;
    padding-bottom: 0;
`;

const StatsElement = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    height: 100%;
`;

const StatsElementBar = styled.div`
    width: 26px;
    height: 100%;
    background-color: #2f4f4f10;
    border-radius: 16px;
    position: relative;
`;

const StatsElementBarInner = styled.div`
    height: 50%;
    width: 100%;
    background-color: #2f4f4f;
    border-radius: 16px;
    position: absolute;
    bottom: 0;
`;

const StatsElementText = styled.div`
    font-size: 11px;
    font-weight: 500;
    color: #aaa;
`;

// vue/src/app/System/components/StatsPanel.vue
<template>
    <div class="wrapper">
        <div class="stats-header">
            <div class="stats-header__title">
                Statystyki (ilość kalorii dziennie)
            </div>
            <div class="stats-header__text">
                Najbliższy plan tygodniowy (01.01.2020 - 07.01.2020)
            </div>
        </div>
        <div class="stats-container">
            <div class="stats-element">
                <div class="stats-element__bar">
                    <div class="bar__inner" />
                </div>
                <div class="stats-element__text">01/01</div>
            </div>
            <div class="stats-element">
                <div class="stats-element__bar">
                    <div class="bar__inner" />
                </div>
                <div class="stats-element__text">01/01</div>
            </div>
            <div class="stats-element">
                <div class="stats-element__bar">
                    <div class="bar__inner" />
                </div>
                <div class="stats-element__text">01/01</div>
            </div>
            <div class="stats-element">
                <div class="stats-element__bar">
                    <div class="bar__inner" />
                </div>
                <div class="stats-element__text">01/01</div>
            </div>
            <div class="stats-element">
                <div class="stats-element__bar">
                    <div class="bar__inner" />
                </div>
                <div class="stats-element__text">01/01</div>
            </div>
            <div class="stats-element">
                <div class="stats-element__bar">
                    <div class="bar__inner" />
                </div>
                <div class="stats-element__text">01/01</div>
            </div>
            <div class="stats-element">
                <div class="stats-element__bar">
                    <div class="bar__inner" />
                </div>
                <div class="stats-element__text">01/01</div>
            </div>
        </div>
    </div>
</template>
<script setup></script>
<style lang="scss" scoped>
.wrapper {
    grid-area: stats;
    background-color: $alpha;
    box-shadow: 0px 6px 24px $alpha-dark;
    border-radius: 16px;
    backdrop-filter: blur(25px);
    padding: 2rem;
    display: flex;
    flex-direction: column;
}

.stats-header {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    flex: 1;

    &__title {
        font-size: 18px;
        font-weight: 800;
    }

    &__text {
        font-size: 12px;
        font-weight: 500;
        color: $typography;
    }
}

.stats-container {
    flex: 4;
    display: flex;
    justify-content: space-between;
    padding: 1rem 0;
    padding-bottom: 0;
}

.stats-element {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    height: 100%;

    &__bar {
        width: 26px;
        height: 100%;
        background-color: $white-accent;
        border-radius: 16px;
        position: relative;
    }

    .bar__inner {
        height: 50%;
        width: 100%;
        background-color: $primary-dark;
        border-radius: 16px;
        position: absolute;
        bottom: 0;
    }

    &__text {
        font-size: 11px;
        font-weight: 500;
        color: $typography;
    }
}
</style>
